Repository jackdomleo7/Checka11y.css, pull requests merged in 2021-01, with the labels that each got.

#85 Created a cross-browser extension
  .browserslistrc
  .gitattributes
  .github/workflows/cypress.yml
  .gitignore
  .stylelintrc
  CONTRIBUTING.md
  README.md
  checka11y.css
  cypress.json
  cypress/integration/a11y_spec.js
  cypress/plugins/index.js
  cypress/support/commands.js
  cypress/support/index.js
  features.md
  package-lock.json
  package.json
  src/_customisation.scss
  src/_helpers.scss
  src/_variables.scss
  src/features/_autoplay.scss
  src/features/_buttons.scss
  src/features/_dir.scss
  src/features/_handlers.scss
  src/features/_headings.scss
  src/features/_html.scss
  src/features/_iframe.scss
  src/features/_images.scss
  src/features/_inline.scss
  src/features/_links.scss
  src/features/_lists.scss
  src/features/_navigation.scss
  src/features/_tabindex.scss
  src/features/_underlinedtext.scss
  src/messages/_content.scss
  src/messages/_vector.scss
  test/index.css
  test/index.html
Labels: project enhancement

#90 Prevent too much inheritance of styles for error/warning messages
  checka11y.css
  src/_customisation.scss
  src/_variables.scss
  src/messages/_content.scss
  src/messages/_vector.scss
Labels: bug

#92 Broken copy warning
  README.md
  src/features/_inline.scss
Labels: a11y feature

#94 Reduce scope of headings check
  checka11y-errors.css
  checka11y.css
  cypress/integration/a11y_spec.js
  src/errors/features/_headings.scss
  test/index.html
Labels: bug
