Repository jackdomleo7/Checka11y.css, pull requests merged in 2021-02, with the labels that each got.

#98 Feature codes
  CONTRIBUTING.md
  README.md
  checka11y-errors.css
  checka11y-warnings.css
  checka11y.css
  codes.md
  cypress/integration/a11y_spec.js
  features.md
  images/code-example.png
  src/errors/features/_buttons.scss
  src/errors/features/_dir.scss
  src/errors/features/_headings.scss
  src/errors/features/_html.scss
  src/errors/features/_iframe.scss
  src/errors/features/_images.scss
  src/errors/features/_links.scss
  src/errors/features/_lists.scss
  src/errors/features/_navigation.scss
  src/errors/features/_tabindex.scss
  src/shared/messages/_content.scss
  src/shared/messages/_vector.scss
  src/warnings/features/_accesskey.scss
  src/warnings/features/_autoplay.scss
  src/warnings/features/_handlers.scss
  src/warnings/features/_images.scss
  src/warnings/features/_inline.scss
  src/warnings/features/_links.scss
  src/warnings/features/_underline.scss
Labels: project enhancement

#99 Warning when using the title attribute
  checka11y-errors.css
  checka11y-warnings.css
  checka11y.css
  codes.md
  features.md
  src/shared/messages/_content.scss
  src/shared/messages/_vector.scss
  src/warnings/checka11y-warnings.scss
  src/warnings/features/_title.scss
  test/index.html
Labels: a11y feature

#100 Elements with aria-hidden should not have focusable descendants
  checka11y-warnings.css
  checka11y.css
  codes.md
  features.md
  src/warnings/checka11y-warnings.scss
  src/warnings/features/_aria-hidden.scss
  test/index.html
Labels: a11y feature

#101 Updated docs website for v1.3.0
  css/checka11y.min.css
  css/docs.min.css
  demo/index.html
  index.html
  package-lock.json
  package.json
  scss/_buy-me-a-coffee.scss
  sitemap.xml
Labels: documentation

#102 Add errors & warnings stylesheet to bundled files
  package.json
Labels: bug

#103 Add tests for each feature
  .github/workflows/cypress.yml
  .gitignore
  README.md
  cypress/integration/a11y_spec.js
  cypress/integration/accesskey_spec.js
  cypress/integration/autoplay_spec.js
  cypress/integration/buttons_spec.js
  cypress/integration/dir_spec.js
  cypress/integration/handlers_spec.js
  cypress/integration/headings_spec.js
  cypress/integration/html_spec.js
  cypress/integration/iframe_spec.js
  cypress/integration/images_spec.js
  cypress/integration/inline_spec.js
  cypress/integration/links_spec.js
  cypress/integration/lists_spec.js
  cypress/integration/navigation_spec.js
  cypress/integration/tabindex_spec.js
  cypress/integration/underline_spec.js
  cypress/support/constants.js
  test/index.html
Labels: project enhancement
